[package]
description = "A logging library."
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]
license = "MIT"
name = "howmanysmall/log"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.1.0"

[dependencies]
